const mongoose = require('mongoose');
const Vehicle = require('../models/Vehicle');
require('dotenv').config();

// Connect to MongoDB
mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/vehicle_rental')
  .then(() => console.log('Connected to MongoDB'))
  .catch(err => console.error('Connection error:', err));

// Vehicles with Indian Rupee pricing - Complete Collection
const vehicles = [
  // ==================== BIKES (₹300 - ₹1500 per day) ====================
  {
    name: "Royal Enfield Classic 350",
    brand: "Royal Enfield",
    model: "Classic 350",
    year: 2023,
    category: "bike",
    subCategory: "cruiser",
    pricePerDay: 800,
    pricePerKm: 5,
    securityDeposit: 5000,
    image: "https://images.unsplash.com/photo-1589106593505-9bf2e9ad8d6c?w=800",
    description: "Iconic British classic motorcycle. Perfect for long rides and weekend getaways. The thump of the Royal Enfield is unmatched.",
    features: ["ABS", "Dual Channel Brakes", "Tubeless Tires", "Retro Design", "Digital Speedometer"],
    transmission: "Manual",
    seats: 2,
    fuelType: "Petrol",
    available: true,
    rating: 4.7,
    driverRequired: false,
    driverPrice: 0,
    allowRideSharing: true,
    maxPassengers: 1,
    isTrackable: true,
  },
  {
    name: "Honda Activa 6G",
    brand: "Honda",
    model: "Activa 6G",
    year: 2023,
    category: "bike",
    subCategory: "scooter",
    pricePerDay: 350,
    pricePerKm: 3,
    securityDeposit: 2000,
    image: "https://images.unsplash.com/photo-1570714964851-8e1b3d2fd20e?w=800",
    description: "India's favorite scooter. Perfect for city commuting and daily use. Easy to ride and very fuel-efficient.",
    features: ["Silent Start", "LED Headlamp", "External Fuel Fill", "Large Storage", "Comfortable Seat"],
    transmission: "Automatic",
    seats: 2,
    fuelType: "Petrol",
    available: true,
    rating: 4.6,
    driverRequired: false,
    allowRideSharing: false,
  },
  {
    name: "KTM Duke 390",
    brand: "KTM",
    model: "Duke 390",
    year: 2023,
    category: "bike",
    subCategory: "sports",
    pricePerDay: 1200,
    pricePerKm: 8,
    securityDeposit: 10000,
    image: "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=800",
    description: "Performance naked sports bike. Extreme power and agility. Perfect for thrill-seekers.",
    features: ["Traction Control", "Quick Shifter", "LED Lights", "TFT Display", "Slipper Clutch"],
    transmission: "Manual",
    seats: 2,
    fuelType: "Petrol",
    available: true,
    rating: 4.8,
    driverRequired: false,
    allowRideSharing: false,
  },
  {
    name: "Bajaj Pulsar NS200",
    brand: "Bajaj",
    model: "Pulsar NS200",
    year: 2023,
    category: "bike",
    subCategory: "sports",
    pricePerDay: 600,
    pricePerKm: 4,
    securityDeposit: 3000,
    image: "https://images.unsplash.com/photo-1589166183027-0c5b5ecf4c73?w=800",
    description: "Aggressive streetfighter design with powerful performance. The wolf of Indian roads.",
    features: ["Perimeter Frame", "Monoshock", "Digital Console", "LED Tail Lamp", "Clip-On Handlebars"],
    transmission: "Manual",
    seats: 2,
    fuelType: "Petrol",
    available: true,
    rating: 4.5,
    driverRequired: false,
  },
  {
    name: "TVS Apache RR 310",
    brand: "TVS",
    model: "Apache RR 310",
    year: 2023,
    category: "bike",
    subCategory: "sports",
    pricePerDay: 1000,
    pricePerKm: 6,
    securityDeposit: 8000,
    image: "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?w=800",
    description: "Fully-faired sports bike with race-inspired dynamics.",
    features: ["Race-Tuned ECU", "Slipper Clutch", "Vertical Console", "Dual Channel ABS"],
    transmission: "Manual",
    seats: 2,
    fuelType: "Petrol",
    available: true,
    rating: 4.7,
  },

  // ==================== CARS (₹1500 - ₹5000 per day) ====================
  {
    name: "Maruti Suzuki Swift",
    brand: "Maruti Suzuki",
    model: "Swift",
    year: 2023,
    category: "car",
    subCategory: "hatchback",
    pricePerDay: 1500,
    pricePerKm: 10,
    securityDeposit: 5000,
    image: "https://images.unsplash.com/photo-1618842676033-0650a32adccd?w=800",
    description: "India's favorite hatchback. Sporty, fuel-efficient, and fun to drive. Perfect for city driving.",
    features: ["Apple CarPlay", "Android Auto", "Rear Camera", "Push Start", "Automatic AC"],
    transmission: "Manual",
    seats: 5,
    fuelType: "Petrol",
    available: true,
    rating: 4.6,
    driverRequired: false,
    driverPrice: 500,
    allowRideSharing: true,
    maxPassengers: 4,
  },
  {
    name: "Hyundai i20",
    brand: "Hyundai",
    model: "i20",
    year: 2023,
    category: "car",
    subCategory: "hatchback",
    pricePerDay: 1800,
    pricePerKm: 12,
    securityDeposit: 7000,
    image: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800",
    description: "Premium hatchback with stunning design and features. Luxury in a compact package.",
    features: ["Sunroof", "BlueLink", "Bose Speakers", "Ventilated Seats", "Wireless Charging"],
    transmission: "Automatic",
    seats: 5,
    fuelType: "Petrol",
    available: true,
    rating: 4.7,
    driverRequired: false,
  },
  {
    name: "Honda City",
    brand: "Honda",
    model: "City",
    year: 2023,
    category: "car",
    subCategory: "sedan",
    pricePerDay: 2500,
    pricePerKm: 15,
    securityDeposit: 10000,
    image: "https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?w=800",
    description: "The legendary sedan. Luxury, comfort, and performance. The ultimate family car.",
    features: ["ADAS", "Lane Watch", "Paddle Shifters", "Rear AC Vents", "Digipad 2.0"],
    transmission: "Automatic",
    seats: 5,
    fuelType: "Petrol",
    available: true,
    rating: 4.8,
    driverRequired: true,
    driverPrice: 800,
  },
  {
    name: "Toyota Innova Crysta",
    brand: "Toyota",
    model: "Innova Crysta",
    year: 2023,
    category: "car",
    subCategory: "mpv",
    pricePerDay: 3500,
    pricePerKm: 18,
    securityDeposit: 15000,
    image: "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800",
    description: "The king of MPVs. Perfect for family trips and group travel. Spacious and reliable.",
    features: ["Captain Seats", "Rear Entertainment", "Climate Control", "Keyless Entry", "7 Airbags"],
    transmission: "Automatic",
    seats: 7,
    fuelType: "Diesel",
    available: true,
    rating: 4.9,
    driverRequired: true,
    driverPrice: 1000,
  },

  // ==================== SUVs (₹3000 - ₹8000 per day) ====================
  {
    name: "Mahindra Thar",
    brand: "Mahindra",
    model: "Thar",
    year: 2023,
    category: "suv",
    subCategory: "off-road",
    pricePerDay: 4000,
    pricePerKm: 20,
    securityDeposit: 20000,
    image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800",
    description: "Iconic off-road SUV. Conquer any terrain with style. The ultimate adventure machine.",
    features: ["4x4", "Convertible Top", "Infotainment", "Roll Cage", "Brake Locking Differential"],
    transmission: "Manual",
    seats: 4,
    fuelType: "Diesel",
    available: true,
    rating: 4.8,
    driverRequired: false,
    allowRideSharing: true,
    maxPassengers: 3,
  },
  {
    name: "Hyundai Creta",
    brand: "Hyundai",
    model: "Creta",
    year: 2023,
    category: "suv",
    subCategory: "compact",
    pricePerDay: 3200,
    pricePerKm: 16,
    securityDeposit: 15000,
    image: "https://images.unsplash.com/photo-1559416523-140ddc3d238c?w=800",
    description: "India's favorite compact SUV. Style meets practicality. Perfect for urban jungle.",
    features: ["Panoramic Sunroof", "Bose Sound", "BlueLink", "Air Purifier", "Ventilated Seats"],
    transmission: "Automatic",
    seats: 5,
    fuelType: "Diesel",
    available: true,
    rating: 4.7,
  },
  {
    name: "Tata Harrier",
    brand: "Tata",
    model: "Harrier",
    year: 2023,
    category: "suv",
    subCategory: "premium",
    pricePerDay: 3800,
    pricePerKm: 18,
    securityDeposit: 18000,
    image: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=800",
    description: "Premium SUV with striking design and powerful engine. Impact design at its best.",
    features: ["Automatic AC", "Air Purifier", "7 Speaker System", "Xenon Lamps", "Sunroof"],
    transmission: "Automatic",
    seats: 5,
    fuelType: "Diesel",
    available: true,
    rating: 4.7,
  },
  {
    name: "MG Hector",
    brand: "MG",
    model: "Hector",
    year: 2023,
    category: "suv",
    subCategory: "premium",
    pricePerDay: 4200,
    pricePerKm: 20,
    securityDeposit: 20000,
    image: "https://images.unsplash.com/photo-1606664512736-37c1ab4a4a2f?w=800",
    description: "Internet-enabled SUV with premium features. The smart SUV for smart people.",
    features: ["Internet Car", "Panoramic Roof", "AI Assistant", "5-Star Safety", "Digital Console"],
    transmission: "Automatic",
    seats: 5,
    fuelType: "Petrol",
    available: true,
    rating: 4.6,
  },

  // ==================== LUXURY CARS (₹8000 - ₹25000 per day) ====================
  {
    name: "Mercedes-Benz E-Class",
    brand: "Mercedes-Benz",
    model: "E-Class",
    year: 2023,
    category: "luxury",
    subCategory: "sedan",
    pricePerDay: 15000,
    pricePerKm: 50,
    securityDeposit: 50000,
    image: "https://images.unsplash.com/photo-1621135802920-133df287f89c?w=800",
    description: "The epitome of luxury and performance. Experience the best that German engineering has to offer.",
    features: ["Massage Seats", "Burmester Audio", "Air Suspension", "Ambient Lighting", "MBUX System"],
    transmission: "Automatic",
    seats: 5,
    fuelType: "Petrol",
    available: true,
    rating: 4.9,
    driverRequired: true,
    driverPrice: 1500,
  },
  {
    name: "BMW 3 Series",
    brand: "BMW",
    model: "3 Series",
    year: 2023,
    category: "luxury",
    subCategory: "sedan",
    pricePerDay: 12000,
    pricePerKm: 45,
    securityDeposit: 40000,
    image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800",
    description: "Ultimate driving machine. Luxury meets performance. Sheer driving pleasure.",
    features: ["M Sport Kit", "Harman Kardon", "Wireless Charging", "Gesture Control", "Laser Lights"],
    transmission: "Automatic",
    seats: 5,
    fuelType: "Petrol",
    available: true,
    rating: 4.8,
    driverRequired: true,
    driverPrice: 1200,
  },
  {
    name: "Audi Q5",
    brand: "Audi",
    model: "Q5",
    year: 2023,
    category: "luxury",
    subCategory: "suv",
    pricePerDay: 14000,
    pricePerKm: 48,
    securityDeposit: 45000,
    image: "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=800",
    description: "Luxury SUV with Quattro technology. Progressive luxury at its finest.",
    features: ["Virtual Cockpit", "Bang & Olufsen", "Panoramic Roof", "Matrix LED", "Quattro Drive"],
    transmission: "Automatic",
    seats: 5,
    fuelType: "Petrol",
    available: true,
    rating: 4.8,
    driverRequired: true,
    driverPrice: 1300,
  },
  {
    name: "Volvo XC90",
    brand: "Volvo",
    model: "XC90",
    year: 2023,
    category: "luxury",
    subCategory: "suv",
    pricePerDay: 18000,
    pricePerKm: 55,
    securityDeposit: 60000,
    image: "https://images.unsplash.com/photo-1603584173870-7f23fdae1b7a?w=800",
    description: "Scandinavian luxury with world-class safety. The safest SUV on the road.",
    features: ["Bowers & Wilkins", "Air Suspension", "Pilot Assist", "CleanZone", "Orrefors Crystal"],
    transmission: "Automatic",
    seats: 7,
    fuelType: "Petrol",
    available: true,
    rating: 4.9,
    driverRequired: true,
    driverPrice: 1600,
  },

  // ==================== ELECTRIC VEHICLES (₹2000 - ₹6000 per day) ====================
  {
    name: "Tata Nexon EV",
    brand: "Tata",
    model: "Nexon EV",
    year: 2023,
    category: "electric",
    subCategory: "suv",
    pricePerDay: 2500,
    pricePerKm: 2,
    securityDeposit: 15000,
    image: "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800",
    description: "India's best-selling electric SUV. Zero emissions, maximum range. The future of mobility.",
    features: ["Fast Charging", "Regenerative Braking", "ZConnect", "Electronic Parking", "Drive Modes"],
    transmission: "Automatic",
    seats: 5,
    fuelType: "Electric",
    available: true,
    rating: 4.7,
    driverRequired: false,
  },
  {
    name: "MG ZS EV",
    brand: "MG",
    model: "ZS EV",
    year: 2023,
    category: "electric",
    subCategory: "suv",
    pricePerDay: 3000,
    pricePerKm: 2.5,
    securityDeposit: 20000,
    image: "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?w=800",
    description: "Premium electric SUV with panoramic sunroof. Electric excitement redefined.",
    features: ["Panoramic Roof", "Panasonic Battery", "iSMART", "Cruise Control", "Fast Charging"],
    transmission: "Automatic",
    seats: 5,
    fuelType: "Electric",
    available: true,
    rating: 4.8,
  },
  {
    name: "Hyundai Kona Electric",
    brand: "Hyundai",
    model: "Kona Electric",
    year: 2023,
    category: "electric",
    subCategory: "suv",
    pricePerDay: 3500,
    pricePerKm: 3,
    securityDeposit: 25000,
    image: "https://images.unsplash.com/photo-1619767886558-efdc259cde1a?w=800",
    description: "Global electric SUV with impressive range. Premium electric experience.",
    features: ["Ventilated Seats", "Sunroof", "BlueLink", "Wireless Charging", "Cruise Control"],
    transmission: "Automatic",
    seats: 5,
    fuelType: "Electric",
    available: true,
    rating: 4.7,
  },

  // ==================== TRUCKS (₹4000 - ₹12000 per day) ====================
  {
    name: "Tata Ace",
    brand: "Tata",
    model: "Ace",
    year: 2023,
    category: "truck",
    subCategory: "mini-truck",
    pricePerDay: 4000,
    pricePerKm: 15,
    securityDeposit: 10000,
    image: "https://images.unsplash.com/photo-1601584115197-04e4d6ff199c?w=800",
    description: "India's favorite small commercial vehicle for goods transport. The champion of last-mile delivery.",
    features: ["1 Ton Capacity", "Fuel Efficient", "Low Maintenance", "Agile", "Durable Build"],
    transmission: "Manual",
    seats: 2,
    fuelType: "Diesel",
    available: true,
    rating: 4.5,
    driverRequired: true,
    driverPrice: 800,
  },
  {
    name: "Ashok Leyland Dost",
    brand: "Ashok Leyland",
    model: "Dost",
    year: 2023,
    category: "truck",
    subCategory: "mini-truck",
    pricePerDay: 5000,
    pricePerKm: 18,
    securityDeposit: 15000,
    image: "https://images.unsplash.com/photo-1601584115197-04e4d6ff199c?w=800",
    description: "Reliable pickup truck for all your transport needs. Strong and dependable.",
    features: ["1.5 Ton Capacity", "Strong Build", "Comfortable Cabin", "Mileage", "Low Maintenance"],
    transmission: "Manual",
    seats: 2,
    fuelType: "Diesel",
    available: true,
    rating: 4.6,
    driverRequired: true,
    driverPrice: 900,
  },
  {
    name: "Mahindra Bolero Pickup",
    brand: "Mahindra",
    model: "Bolero Pickup",
    year: 2023,
    category: "truck",
    subCategory: "pickup",
    pricePerDay: 6000,
    pricePerKm: 20,
    securityDeposit: 18000,
    image: "https://images.unsplash.com/photo-1601584115197-04e4d6ff199c?w=800",
    description: "Heavy-duty pickup for commercial use. Tough terrain, tougher performance.",
    features: ["2.5 Ton Capacity", "Powerful Engine", "High Ground Clearance", "Durable Suspension"],
    transmission: "Manual",
    seats: 2,
    fuelType: "Diesel",
    available: true,
    rating: 4.6,
    driverRequired: true,
    driverPrice: 1000,
  },

  // ==================== SELF-DRIVING VEHICLES (₹6000 - ₹15000 per day) ====================
  {
    name: "Tesla Model 3 (Self-Driving)",
    brand: "Tesla",
    model: "Model 3",
    year: 2023,
    category: "self-driving",
    subCategory: "autonomous",
    pricePerDay: 10000,
    pricePerKm: 5,
    securityDeposit: 50000,
    image: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800",
    description: "Fully autonomous driving experience. The future is here. Let the car do the driving.",
    features: ["Full Self-Driving", "Autopilot", "Summon", "Auto Lane Change", "Smart Summon", "Parking Assist"],
    transmission: "Automatic",
    seats: 5,
    fuelType: "Electric",
    available: true,
    rating: 4.9,
    driverRequired: false,
    isTrackable: true,
    allowRideSharing: true,
    maxPassengers: 4,
  },
  {
    name: "Waymo Autonomous SUV",
    brand: "Waymo",
    model: "Chrysler Pacifica",
    year: 2023,
    category: "self-driving",
    subCategory: "autonomous",
    pricePerDay: 12000,
    pricePerKm: 6,
    securityDeposit: 60000,
    image: "https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800",
    description: "Fully autonomous minivan for group travel. Experience true driverless technology.",
    features: ["Lidar Sensors", "Radar System", "360° Cameras", "Voice Control", "Auto-Door Open"],
    transmission: "Automatic",
    seats: 7,
    fuelType: "Electric",
    available: true,
    rating: 4.8,
    driverRequired: false,
    isTrackable: true,
  },
];

async function seedVehicles() {
  try {
    // Clear existing vehicles
    await Vehicle.deleteMany();
    console.log('🗑️ Cleared existing vehicles');
    
    // Insert new vehicles
    const result = await Vehicle.insertMany(vehicles);
    console.log(`✅ Successfully added ${result.length} vehicles to the database!`);
    
    // Display statistics
    console.log('\n📊 Vehicle Statistics:');
    console.log('='.repeat(60));
    
    const stats = {};
    vehicles.forEach(v => {
      if (!stats[v.category]) {
        stats[v.category] = { count: 0, minPrice: Infinity, maxPrice: -Infinity };
      }
      stats[v.category].count++;
      stats[v.category].minPrice = Math.min(stats[v.category].minPrice, v.pricePerDay);
      stats[v.category].maxPrice = Math.max(stats[v.category].maxPrice, v.pricePerDay);
    });
    
    const categoryNames = {
      bike: '🏍️ Bikes',
      car: '🚗 Cars',
      suv: '🚙 SUVs',
      luxury: '💎 Luxury Cars',
      electric: '⚡ Electric Vehicles',
      truck: '🚚 Trucks',
      'self-driving': '🤖 Self-Driving Cars'
    };
    
    Object.entries(stats).forEach(([category, data]) => {
      console.log(`${categoryNames[category] || category}: ${data.count} vehicles`);
      console.log(`   💰 Price Range: ₹${data.minPrice.toLocaleString('en-IN')} - ₹${data.maxPrice.toLocaleString('en-IN')}/day`);
    });
    
    // Show sample vehicles
    console.log('\n📋 Sample Vehicles:');
    console.log('='.repeat(60));
    vehicles.slice(0, 5).forEach(v => {
      console.log(`• ${v.name}: ₹${v.pricePerDay.toLocaleString('en-IN')}/day (${v.category})`);
    });
    
    console.log(`\n✨ Total vehicles in database: ${result.length}`);
    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    process.exit(1);
  }
}

seedVehicles();